export const ADD_SCORE = 'ADD_SCORE';
export const REQUEST_SCORES = 'REQUEST_SCORES';
export const FAILED_SCORE = 'FAILED_SCORE';
export const RECEIVE_SCORES = 'RECEIVE_SCORES';

export const ADD_COMMENT = 'ADD_COMMENT';
export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const FAILED_COMMENT = 'FAILED_COMMENT';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';

